
run: out/Assignment6.class out/MazeNode.class out/Search.class
	java -cp out Assignment6

out/Assignment6.class: Assignment6.java
	javac Assignment6.java -d out/

out/MazeNode.class: MazeNode.java
	javac MazeNode.java -d out/

out/Search.class: Search.java
	javac Search.java -d out/

