
main: out/AssignmentConfig.class out/Policy.class out/RandomPolicy.class out/GreedyPolicy.class out/QLearningPolicy.class out/Assignment8.class 
	java -cp out Assignment8

out/Assignment8.class: Assignment8.java
	javac -d out Assignment8.java

out/AssignmentConfig.class: AssignmentConfig.java
	javac -d out AssignmentConfig.java

out/Policy.class: Policy.java
	javac -d out Policy.java

out/RandomPolicy.class: RandomPolicy.java
	javac -d out RandomPolicy.java

out/GreedyPolicy.class: GreedyPolicy.java
	javac -d out GreedyPolicy.java

out/QLearningPolicy.class: QLearningPolicy.java
	javac -d out QLearningPolicy.java

